language: scala

scala:
- 2.12.2
- 2.11.11

jdk:
- oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom source-map-support jsdom-global

env:
  global:
    JSENV=node

script:
  - sbt ++$TRAVIS_SCALA_VERSION testDev testProd


deploy:
  provider: script
  script:
  - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    tags: true

env:
  global:
  # travis encrypt BINTRAY_USER=xxx
  - secure: "sfMeZNmRorUfPBvUZc+EskKXmJJVMPXkUuA2uUO53V2wVa2DidQbJB+EQKXUhCA9sTQxvAd1vkbE3WFhm0NnrfA+Ishdzyo5XYgQ0S2Q58CT8YWJPJzZgSceqVPR9RVjBzQ7WGKzA+GO4ud/ZxCxifVSz76X08TY1GK1+ynAtlVEaPLEsQsRalD3Ud84DUUsI+OFPz7ymgLQcolVHMtsBnS2GyUGFwMToWvtXV8y/7Z9iE7bacDpwzx7z20xSQmnI4rQR1Y9OB7jwRpthNo5IaizFy5OL8AgeNOxV6wzQatB7H+7266ANxBxqGICDgUxN3PvqDeZqelgk1h3DCeUAx86T1kwbq8yS9v9fkfJ1FbmD17hXTwJzoWPsTbIK7XuuSwFhwrIV1HBSLkTS6zJZ8XK3NusJ/adoTIfh1EIfzaEnxjVYRjCnLdOgwymxUT/WiMVnUWFQu3hfIv9sClZmL7kVPzXC3rK1wzZ67FXX+mMpfy1DEJfkJm0slI+Nc1AFJecpO00zQFup8DXRr7SFqt5LYtAZrIVmQJ3lhgmMW0+Am+J6ay33xPIRyM61/ODdm9GJlbg6kqC9FZvA6380weifo7HH4MTC29qUBrSqxm4YTljCi1lS9GsfIOAMRy7aTTO52f4k8DhkbygpqB73/APB5m3FjbuJr5iwESa6LU="
  # travis encrypt BINTRAY_PASSWORD=xxx
  - secure: "bt876ueLLW/at75m1rHdnDZXJJwgJUieljbgX+afdgqcBjJ1UzZb2jvIKxzlZcroHkG9sg6fc5FSBDdjXpiuqFnLT9ESpup9bos9hd4J/f+OH/kM6uU/i9keIx89bLJ8BWZSuQyOruOC3Pc71dDvcyd53yY7YqdSlM3XWc9dmlN5wAK6WR4Hp455p8MyN2oZ63yGQf2MiyMxMogGIB6ABoFim2K9L9r1elz4nrFKWLVEXK/9BIQMnvRdT0UwF7RQwlzmHbImIYjpbXkVVqNoKoJAUpyvBP/7BOqpgJntP1Ysla6IWXdWTUE7wu3/ZjHKoCTYi6AS516vwGUUvGy5ORy2M1TNU/1VYOrlUgyKKj2WoqJ0hXBVsZX/DIZFANil8Mcif5Jalt/LNOlbIuE8YbzUkk7lFxBUpZz8ppQgYpnY4LcJEEQfcdI6RERHxujI54PykO0zxowSjUci1iyGqoOhvto+uqVOShUro65XtM0a7sS1xI16EGOeNKYSPqA7KiqDODSpHThAewfgiOiiO+60zTE+sDqVl8vA8SR55ZQLw1oBKFvj54m+OxJyC0KgPyF3kQw++2VoeoXM7yP01NRxdgBjSKd3lV/JDyhtn5binKTy5DgOLpBxUPgZhDnAApzDwpOW5wsoJBdHb4FyRD//lQ/zndutG72vIe1I/Gk="

