language: scala

scala:
- 2.12.2
- 2.11.11

jdk:
- oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom source-map-support jsdom-global

env:
  global:
    JSENV=node

script:
  - sbt ++$TRAVIS_SCALA_VERSION test:fastOptJS test:fullOptJS
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' 'set scalaJSStage in ThisBuild := FullOptStage' test


deploy:
  provider: script
  script:
  - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    tags: true

env:
  global:
  # travis encrypt BINTRAY_USER=xxx
  - secure: "paZO+JREKPt5aKN0227HslsSxNoeM6eZaQL9RbuVX3L07AsmppGnC0vRu0Fy3J+XtK+5ulPMZKDBtUnbfriv0dFXEQ7Sf4O0E3HVYdj495KQtrf9ki2K1nSe5bbdX0SDJdQGMJ1GbS2c2GPACIrivoz1SKVXqtLz/Ytq5dqSRK58S6sELxvle9euHYxoBQnsgOAF27JbTcOjJYBUXIVXEnCWKEM5GH2AJVLyM+A0RvqsPgTIgWj1a0AxXLTSx4ifciYtObm2MWk/JaJ/f0xaMKVw+ZRYjK3ihXUTExGd6FJdsbo3MmWMYF2ypp9/9xzb//L2Kjr3aJYKFhkhwuReLbe4NQ1VnHhtW/a4mGpmZ96F/KNO4RDEuYg6Xm1KuUbwEKh6qvZ9dym2Fr4WCakLhja9/x/Opu946/XSgebkpysYy1PPf09EKAztw0JkBtj1DnX95KUEB2CYnTAhgeRyBdj8e2v898MtAqQ71cf016SUXr4CT2rrQvRnxNJOxCZfnslEw2DEcOHYLVG8mD5FCaM7oLmaPCGGoq9mOTzhVN8kIipnRYTyIxGn38Aaqwuii2kFNz58xWuWzIHtg+ajSzgFtUsj/iaYd2GWem4TVnK88L8DPrNbeEohrSF650xlmU252ue8HpWAfLh0mlJfmtvknvNsBvsGQOESMn2RDss="
  # travis encrypt BINTRAY_PASSWORD=xxx
  - secure: "YskRPfBa5ckfbsU3qScTw+LbT/vZQMUzPyQNCJbo8f7ee/5guPm+ctwiRDRXvWBAdBoC15GlOLPOPOUabs9WMhGwMYyQQl8dEjL8Deeslur5jEEIRthuX8SrrRe78boasegRqVUQBZeii2Nju7oNPnw3ajks9Bvm+J8LXgG5fCAVQ24lbytl82qGKCpD3AVnArSJMtMMpojoWTJOpYQrBpJHogAAtdBhrBNVOfY3LHJ9HycERKq7j0eec/SEI4o916C+ETrPPxl1OShIv4X9rNlh5aejd6zk54TK0DJU7qBh3dQnI1dqsgv40Ba7wzCP72mi/wzEFzgdjrRQZIOW5zrs+hF8+zo/GjtqdakfCyv7JYLCh5+UlNFgm6D7RjEzDqikNQZtfcTi7HySCbE959IHw6Nrk+8qhWFIJbx2+Mz7zWTDmONsi8/A2uIwijTy+0PHDe0EO1kZcBNckfncJ0Ql/N0Awwx+YX3fof9BFgmmlxrFHlQ4EtU3AacsC7K3IJHv3Mq2gtWTlxN/8gCL7MTxXeNzlLvQFa6fDXB/H9GSb22kuksOLUKl32Lfs1/DKqS33hABo1x+wR5HtnFmxoAtcrXWFSa9TajNadkCzobZ52YRUB4yayfB2KsSzDLkCXSG7Tv2Rpl+z56nunlPJDVeHys1mCbczOHpPPsOlW4="

